name: Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs-site/package.json

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: other

      - name: Generate docs-site configuration
        run: |
          # Create docs-site directory
          mkdir -p docs-site/src/css

          # Generate package.json
          cat > docs-site/package.json << 'EOF'
          {
            "name": "documcp-docs",
            "version": "0.0.0",
            "private": true,
            "scripts": {
              "docusaurus": "docusaurus",
              "start": "docusaurus start",
              "build": "docusaurus build",
              "swizzle": "docusaurus swizzle",
              "deploy": "docusaurus deploy",
              "clear": "docusaurus clear",
              "serve": "docusaurus serve --port 3001"
            },
            "dependencies": {
              "@docusaurus/core": "^3.0.0",
              "@docusaurus/preset-classic": "^3.0.0",
              "@mdx-js/react": "^3.0.0",
              "clsx": "^2.0.0",
              "prism-react-renderer": "^2.1.0",
              "react": "^18.0.0",
              "react-dom": "^18.0.0"
            },
            "devDependencies": {
              "@docusaurus/types": "^3.0.0"
            }
          }
          EOF

          # Generate docusaurus.config.js
          cat > docs-site/docusaurus.config.js << 'EOF'
          module.exports = {
            title: "DocuMCP",
            tagline: "Intelligent Model Context Protocol server for documentation deployment",
            url: "https://tosin2013.github.io",
            baseUrl: "/documcp/",
            onBrokenLinks: "warn",
            onBrokenMarkdownLinks: "warn",
            favicon: "img/favicon.ico",
            organizationName: "tosin2013",
            projectName: "documcp",

            presets: [
              [
                "classic",
                {
                  docs: {
                    sidebarPath: require.resolve("./sidebars.js"),
                    editUrl: "https://github.com/tosin2013/documcp/tree/main/docs/",
                    path: "../docs",
                    routeBasePath: "/",
                  },
                  theme: {
                    customCss: require.resolve("./src/css/custom.css"),
                  },
                  blog: false,
                },
              ],
            ],

            themeConfig: {
              navbar: {
                title: "DocuMCP",
                items: [
                  {
                    type: "doc",
                    docId: "index",
                    position: "left",
                    label: "Documentation",
                  },
                  {
                    href: "https://github.com/tosin2013/documcp",
                    label: "GitHub",
                    position: "right",
                  },
                ],
              },
            },

            exclude: [
              "**/node_modules/**",
              "**/.docusaurus/**",
              "**/build/**",
              "**/package.json",
              "**/package-lock.json",
            ],
          };
          EOF

          # Generate sidebars.js
          cat > docs-site/sidebars.js << 'EOF'
          /** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
          const sidebars = {
            docs: [
              "index",
              {
                type: "category",
                label: "Tutorials",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "tutorials",
                  },
                ],
              },
              {
                type: "category",
                label: "How-to Guides",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "how-to",
                  },
                ],
              },
              {
                type: "category",
                label: "Reference",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "reference",
                  },
                ],
              },
              {
                type: "category",
                label: "Explanation",
                items: [
                  {
                    type: "autogenerated",
                    dirName: "explanation",
                  },
                ],
              },
            ],
          };

          module.exports = sidebars;
          EOF

          # Generate custom.css
          cat > docs-site/src/css/custom.css << 'EOF'
          :root {
            --ifm-color-primary: #2e8555;
            --ifm-color-primary-dark: #29784c;
            --ifm-color-primary-darker: #277148;
            --ifm-color-primary-darkest: #205d3b;
            --ifm-color-primary-light: #33925d;
            --ifm-color-primary-lighter: #359962;
            --ifm-color-primary-lightest: #3cad6e;
            --ifm-code-font-size: 95%;
            --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.1);
          }

          [data-theme="dark"] {
            --ifm-color-primary: #25c2a0;
            --ifm-color-primary-dark: #21af90;
            --ifm-color-primary-darker: #1fa588;
            --ifm-color-primary-darkest: #1a8870;
            --ifm-color-primary-light: #29d5b0;
            --ifm-color-primary-lighter: #32d8b4;
            --ifm-color-primary-lightest: #4fddbf;
            --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.3);
          }
          EOF

      - name: Install dependencies
        run: cd docs-site && npm ci

      - name: Build documentation
        run: cd docs-site && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-site/build

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4